[package]
name = "transact"
version = "0.1.1"
authors = ["Bitwise IO, Inc."]
edition = "2018"
license = "Apache-2.0"
readme = "../README.md"
description = """\
    Transact is a transaction execution platform designed to be used as \
    a library or component when implementing distributed ledgers, including \
    blockchains.
"""

[dependencies]
hex = "0.3"
protobuf = "2"
rand = "0.6"
sha2 = "0.8"
lmdb-zero = ">=0.4.1"
log = { version = "0.4", features = ["std"] }
cbor-codec = "0.7"
libc = ">=0.2.35"
openssl = "0.10"
uuid = { version = "0.7", features = ["v4"] }
sawtooth-sdk = { git = "https://github.com/hyperledger/sawtooth-sdk-rust", optional = true }

[dev-dependencies]
rand_hc = "0.1"
sawtooth-xo = { git = "https://github.com/hyperledger/sawtooth-sdk-rust" }

[build-dependencies]
protoc-rust = "2"

[features]
default = []
nightly = []
sawtooth-compat = ["sawtooth-sdk"]
