[package]
name = "transact"
version = "0.2.1"
authors = ["Bitwise IO, Inc.", "Cargill Incorporated"]
edition = "2018"
license = "Apache-2.0"
readme = "../README.md"
description = """\
    Transact is a transaction execution platform designed to be used as \
    a library or component when implementing distributed ledgers, including \
    blockchains.
"""
repository = "http://github.com/hyperledger/transact"

[dependencies]
cbor-codec = { version = "0.7", optional = true }
hex = "0.3"
libc = ">=0.2.35"
lmdb-zero = ">=0.4.1"
log = { version = "0.4", features = ["std"] }
openssl = "0.10"
protobuf = "2"
r2d2 = { version = "0.8", optional = true }
r2d2_sqlite = { version = "0.14", optional = true }
rand = "0.6"
redis = { version = "0.13.0", default-features = false, optional = true }
rusqlite = { version = "0.21.0", optional = true }
sawtooth-sdk = { version = "0.3", optional = true }
sha2 = "0.8"
ursa = { version = "0.2.0", optional = true }
uuid = { version = "0.7", features = ["v4"] }

[dev-dependencies]
rand_hc = "0.1"
sawtooth-xo = "0.3"

[build-dependencies]
protoc-rust = "2"

[features]
default = ["state-merkle"]

nightly = []

experimental = [
    "contract",
    "contract-address",
    "contract-address-double-key-hash",
    "contract-address-key-hash",
    "contract-address-triple-key-hash",
    "contract-context",
    "contract-context-key-value",
    "key-value-state",
    "redis-db",
    "sqlite-db"
]

contract = []
contract-address = ["contract"]
contract-address-key-hash = ["contract-address"]
contract-address-double-key-hash = ["contract-address"]
contract-address-triple-key-hash = ["contract-address"]
contract-context = ["contract", "contract-address"]
contract-context-key-value = ["contract-context", "key-value-state"]
key-value-state = []
redis-db = ["redis"]
sawtooth-compat = ["sawtooth-sdk"]
sqlite-db = ["rusqlite", "r2d2", "r2d2_sqlite"]
state-merkle = ["cbor-codec"]
ursa-compat = ["ursa"]

[package.metadata.docs.rs]
features = [
  "default",
  "nightly",
  "experimental",
  "sawtooth-compat",
]
