[package]
name = "transact"
version = "0.1.0"
authors = ["Bitwise IO, Inc."]
edition = "2018"

[dependencies]
hex = "0.3"
log = "0.4"
protobuf = "2"
sha2 = "0.8"

[dev-dependencies]
sawtooth-sdk = "0.1"

[build-dependencies]
protoc-rust = "2"

[features]
nightly = []
