[package]
name = "transact"
version = "0.1.0"
authors = ["Bitwise IO, Inc."]
edition = "2018"

[dependencies]
hex = "0.3"
protobuf = "2"
sha2 = "0.8"
lmdb-zero = ">=0.4.1"
cpython = "0.2"
log = { version = "0.4", features = ["std"] }
python3-sys = "0.2"

[dev-dependencies]
sawtooth-sdk = "0.1"

[build-dependencies]
protoc-rust = "2"

[features]
nightly = []
