[package]
name = "transact"
version = "0.1.0"
authors = ["Bitwise IO, Inc."]
edition = "2018"

[dependencies]
hex = "0.3"
protobuf = "2"

[dev-dependencies]
sawtooth-sdk = "0.1"

[build-dependencies]
protoc-rust = "2"
